In [6]:
import pandas as pd
album_sales = pd.read_csv('albumsales.csv')

album_sales.info()
print(album_sales)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    640 non-null    int64
 1   Artist                  640 non-null    object
 2   Album                   640 non-null    object
 3   Worldwide Sales (Est.)  640 non-null    object
 4   Genre                   640 non-null    object
dtypes: int64(1), object(4)
memory usage: 25.1+ KB
     Year                   Artist                                   Album  \
0    2019                   Arashi           5x20 All The Best!! 1999-2019
1    2017               Elton John                                Diamonds
2    1995          Michael Jackson  History: Past, Present & Future Book I
3    2015      Broadway Soundtrack                                Hamilton
4    2003                  Outkast           Speakerboxxx / The Love Below
..    ...                      ...                                     ...
635  1994         Movie Soundtrack                           The Lion King
636  1996         Movie Soundtrack                         Raja Hindustani
637  1997         Movie Soundtrack                        Dil To Pagal Hai
638  1997  Buena Vista Social Club                 Buena Vista Social Club
639  2000                     Enya                      A Day Without Rain

    Worldwide Sales (Est.)    Genre
0                3,300,000      Pop
1                3,220,000     Rock
2               20,000,000      Pop
3                4,835,000  Hip Hop
4                7,012,000  Hip Hop
..                     ...      ...
635             14,522,893    World
636             11,000,000    World
637             12,500,000    World
638             12,000,000    World
639             12,097,445    World

[640 rows x 5 columns]

In [ ]:
# SQL 
# SELECT 
# 	"Year", 
# 	"Album", 
# 	"WorldwideSales(Est.)"
# From albumsales
# ORDER BY YEAR ASC

#Deleting rows from before 2010
# DELETE 
# FROM albumsales
# WHERE YEAR < 2010;

# DELETE
# FROM albumsales
# WHERE YEAR > 2020;

# #list going from 2010s to 2020
# SELECT *
# FROM albumsales
# ORDER BY YEAR ASC

In [2]:
import pandas as pd
import sqlite3


con = sqlite3.connect('./sqlalbumsales.db')
album_sales = pd.read_sql_query('Select * from albumsales Order by Year ASC', con)

album_sales

,Year,Artist,Album,WorldwideSales(Est.),Genre
0,2010,Eminem,Recovery,"7,740,795",Hip Hop
1,2010,Kanye West,My Beautiful Dark Twisted Fantasy,"3,588,000",Hip Hop
2,2010,Taylor Swift,Speak Now,"6,917,500",Country
3,2010,Jason Aldean,My Kinda Party,"4,115,000",Country
4,2010,Katy Perry,Teenage Dream,"11,094,000",Pop
...,...,...,...,...,...
215,2020,BTS,Be,"5,397,015",Pop
216,2020,Taylor Swift,Folklore,"4,115,487",Pop
217,2020,Dua Lipa,Future Nostalgia,"3,332,300",Pop
218,2020,Blackpink,The Album,"2,947,398",Pop
219,2020,The Weeknd,After House,"4,402,942",R&B

In [ ]:
import pandas as pd 
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.title("Greatest Album of the 2010's", fontdict={'fontweight': 'bold', 'fontsize':14})


plt.plot(album_sales.Year, album_sales.WorldWideSales(Est.), 'r.-', label=2010)

plt.